version: '3.8'

services:
  app:
    # .........
  db:
    # ........
networks:
  my-net:
    # ........
volumes:
  db-data:
    # ........
configs:
  config-name:
    # ........
secrets:
  secret-name:
    # ........


#########################

services:
  web:
    image: nginx:1.23-alpine
    # OR
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      args:
        BUILD_VERSION: 1.0
      labels:
        - "com.example.description=Best application"
    container-name: php_api_app
    working_dir: /app
    ports:
      - "80:80"
      - "443:443/tcp"
      - "8080-8090:3000-3010"
      - "9000"                # рандомный порт на хосте
    expose:
      - 3000
      - 8000
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: appuser
      MYSQ_PASSWORD: userpassword
      - DEBUG=1               # Вариант
    env_file:
      - .env
      - ./config/database.env
    volumes:
      - db_data:/var/lib/mysql    # Named volume
      - logs:/var/logs/app        # Named volume
      - ./data:/app/data          # Bind mount
      - /tmp
      - ./config:/etc/config:ro   # Readonly !!!
      - data_volume:/app/data:rw  # read-write !!!
    depends_on:
      - database
    command: ["npm", "start"]
    entrypoint: /docker-entrypoint.sh
  database:
    image: mysql
    

volumes:
  db_data:
    driver: local
  logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.1,rw
      device: ":/var/app/volume"




